### ISSUE TITLE
Possible name conflict with Craft 3.5+

### ISSUE THREAD

**Issue by frank-laemmer** [ostark/craft-plugin-commands#3]
I see the Craft CLI changed the structure of it's CLI commands. It's now also `craft plugin/install`. I have not tested this, but it might conflict with this plugin maybe?

Side note: There is also an additional `craft plugin/uninstall` now which was one of the main reasons to use this plugin for me.

**Comment by ostark** [comment]
1. No naming conflict, the package overwrites the core.
2. This package is not a plugin
3. Thanks for taking care
